<?php
// Convert Natural Earth 110m land GeoJSON into a compact JS `LAND` array.
// Usage: php tools/convert-land.php <input.geojson> <output.js>

if (PHP_SAPI !== 'cli') { http_response_code(403); exit('CLI only'); }

$in  = $argv[1] ?? '/tmp/ne_110m_land.geojson';
$out = $argv[2] ?? '/tmp/land.js';

$geo = json_decode(file_get_contents($in), true);
if (!$geo || empty($geo['features'])) { fwrite(STDERR, "no features\n"); exit(1); }

const QUANT  = 10;     // 1 decimal place
const DP_TOL = 0.35;   // Douglas-Peucker tolerance (degrees)
const MIN_RING_AREA = 0.15; // drop specks smaller than ~0.15 deg^2
const MIN_HOLE_AREA = 0.25; // only keep meaningful holes (Caspian etc.)

function ringArea(array $r): float {
    $n = count($r); $a = 0.0;
    for ($i = 0; $i < $n; $i++) {
        [$x1,$y1] = $r[$i];
        [$x2,$y2] = $r[($i+1)%$n];
        $a += $x1*$y2 - $x2*$y1;
    }
    return abs($a) / 2;
}

function quantize(array $r): array {
    $q = [];
    foreach ($r as $p) {
        $x = round($p[0]*QUANT)/QUANT;
        $y = round($p[1]*QUANT)/QUANT;
        if (!$q || $q[count($q)-1][0] !== $x || $q[count($q)-1][1] !== $y) $q[] = [$x,$y];
    }
    return $q;
}

function perpDist(array $a, array $b, array $p): float {
    $dx=$b[0]-$a[0]; $dy=$b[1]-$a[1];
    $len2=$dx*$dx+$dy*$dy;
    if ($len2 === 0.0) return hypot($p[0]-$a[0], $p[1]-$a[1]);
    $t = (($p[0]-$a[0])*$dx + ($p[1]-$a[1])*$dy) / $len2;
    $t = max(0.0, min(1.0, $t));
    $x = $a[0]+$t*$dx; $y = $a[1]+$t*$dy;
    return hypot($p[0]-$x, $p[1]-$y);
}

function douglasPeucker(array $pts, float $eps): array {
    if (count($pts) <= 2) return $pts;
    $dmax = 0; $idx = 0;
    $end = count($pts)-1;
    for ($i = 1; $i < $end; $i++) {
        $d = perpDist($pts[0], $pts[$end], $pts[$i]);
        if ($d > $dmax) { $dmax = $d; $idx = $i; }
    }
    if ($dmax > $eps) {
        $l = douglasPeucker(array_slice($pts,0,$idx+1), $eps);
        $r = douglasPeucker(array_slice($pts,$idx), $eps);
        array_pop($l);
        return array_merge($l,$r);
    }
    return [$pts[0], $pts[$end]];
}

function fmtNum(float $v): string {
    $s = number_format($v, 1, '.', '');
    return $s;
}

$features = [];
foreach ($geo['features'] as $f) {
    $geom = $f['geometry'];
    $polys = $geom['type'] === 'Polygon' ? [$geom['coordinates']] : $geom['coordinates'];
    $featRings = [];
    foreach ($polys as $poly) {
        $rings = [];
        foreach ($poly as $ri => $ringRaw) {
            $ring = quantize($ringRaw);
            // Skip Antarctica — the reference style omits it.
            $maxLat = -90;
            foreach ($ring as $p) { if ($p[1] > $maxLat) $maxLat = $p[1]; }
            if ($maxLat < -60) continue;
            $ring = douglasPeucker($ring, DP_TOL);
            if (count($ring) < 4) continue;
            $rings[] = $ring;
        }
        if (!$rings) continue;
        $outerArea = ringArea($rings[0]);
        if ($outerArea < MIN_RING_AREA) continue;
        // keep outer + meaningful holes
        $keep = [$rings[0]];
        for ($i = 1; $i < count($rings); $i++) {
            if (ringArea($rings[$i]) > MIN_HOLE_AREA) $keep[] = $rings[$i];
        }
        $featRings[] = $keep;
    }
    if ($featRings) $features[] = $featRings;
}

// Sort by outer-ring area descending so big landmasses come first.
usort($features, function($a,$b){
    return ringArea($b[0][0]) <=> ringArea($a[0][0]);
});

$lines = [];
$lines[] = "// Generated by tools/convert-land.php from Natural Earth 110m land (public domain).";
$lines[] = "// Feature = list of rings (outer rings + holes, e.g. Caspian); ring = [lon,lat] pairs.
// Rendered with fill-rule=evenodd so holes punch through.";
$lines[] = "const LAND=[";
$pointTotal = 0;
foreach ($features as $fi => $feat) {
    if ($fi > 0) $lines[] = "";
    $lines[] = "  [ // feature " . ($fi+1);
    foreach ($feat as $ri => $rings) {
        $ringStrs = [];
        foreach ($rings as $ring) {
            $pts = [];
            foreach ($ring as $p) { $pts[] = '['.$p[0].','.$p[1].']'; $pointTotal++; }
            $ringStrs[] = '['.implode(',', $pts).']';
        }
        $lines[] = "    ".implode(",\n    ", $ringStrs) . ($ri < count($feat)-1 ? "," : "");
    }
    $lines[] = "  ]" . ($fi < count($features)-1 ? "," : "");
}
$lines[] = "];";

$js = implode("\n", $lines) . "\n";
file_put_contents($out, $js);
fwrite(STDERR, "features=" . count($features) . " points=" . $pointTotal . " bytes=" . strlen($js) . "\n");
